language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7

sudo: false
before_install:
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script: pytest

after_success:
  - pytest --cov=saf
  - codecov

cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
